# Netlify config for Next.js (App Router)
# Açıklama: Next.js SSR/ISR için Netlify resmi eklentisini kullanır.

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
